name: pennyworth_builder
description: OpenApi code generator for Alfred
version: 0.1.0-beta
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  alfred: ^1.1.0
  pennyworth:
    # path: ../pennyworth
    git:
      url: https://github.com/d-markey/pennyworth.git
  async: ^2.10.0
  build: ^2.3.1
  source_gen: ^1.2.7
  analyzer: ^5.7.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  build_runner: ^2.3.3
